### ISSUE TITLE
Q: Theory

### ISSUE THREAD

**Issue by KingKnecht** [sid-code/boolalg#2]
Hi,
are there any background information available about the algorithm you are using?
Thx,
Sven

**Comment by sid-code** [comment]
I'm using an ad-hoc simplification algorithm; it aims to work similarly to how humans simplify boolean algebra expressions. I can't tell you much about it because I pretty much came up with as I was writing the code. However, arbitrary boolean algebra simplification is NP-hard. My algorithm runs in polynomial time, therefore it is incorrect. Indeed, it cannot simplify certain terms (I used to know where it fails, but I've long forgotten that now).

If you want a correct algorithm for this problem, I'd recommend looking at [Karnaugh maps](http://www.ee.surrey.ac.uk/Projects/Labview/minimisation/karnaugh.html).

I'd be happy to answer any specific questions you have.

**Comment by KingKnecht** [comment]
I know about Karnaugh maps (or Quine McCluskey) . The problem with Karnaugh maps is when there are "many" variables approx > 14. It's ok if the result is not the 100% normal form. Do you remember if your algorithm has any problem with endless looping? E.g. substitute, re-substitute, substitute, ...?
I have attached a real-life example from the automotive industry as a (stress)test case for your code. I have already converted it to your input syntax. Just if you are interested :-)
[bool_expression_big.txt](https://github.com/sid-code/boolalg/files/3534548/bool_expression_big.txt)


Thx,
Sven 

Edit: Uploaded wrong file

**Comment by sid-code** [comment]
Ah, I somehow totally forgot to respond to this. I actually did try that input file, and that made me realize how truly terrible this program is. It's definitely going into an infinite loop somewhere, and it's definitely not worth investigating. Thanks for providing that file, it was an interesting exercise!
